const state={upcoming:[],results:[],dayFilter:"all",stageFilter:"all",search:"",favoriteTeam:"",favoriteOnly:false,showAllUpcoming:false,showAllResults:false,teamMeta:new Map()};
const favoriteStorageKey="worldCupFavoriteTeam";
const knockoutRounds=["Round of 32","Round of 16","Quarter-final","Semi-final","Final"];
const roundLabels={"Round of 32":"Son 32","Round of 16":"Son 16","Quarter-final":"Çeyrek final","Semi-final":"Yarı final",Final:"Final","Third place":"Üçüncülük maçı"};
const teamAliases={morroco:"Morocco",morrocco:"Morocco",marocco:"Morocco",brasil:"Brazil",quatar:"Qatar",swiss:"Switzerland",swizerland:"Switzerland",switzerand:"Switzerland","czech republic":"Czechia",equador:"Ecuador",usa:"United States","u.s.a.":"United States"};
const $=id=>document.getElementById(id);
const normalize=value=>String(value||"").trim().toLocaleLowerCase("en-US");
const canonicalTeam=value=>teamAliases[normalize(value)]||String(value||"").trim();
const normalizeGroup=value=>String(value||"").replace(/^group\s+/i,"").trim().toUpperCase();
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function splitCsvLine(line){const cells=[];let cell="",quoted=false;for(let index=0;index<line.length;index+=1){const character=line[index];if(character==='"'&&quoted&&line[index+1]==='"'){cell+='"';index+=1}else if(character==='"')quoted=!quoted;else if(character===","&&!quoted){cells.push(cell);cell=""}else cell+=character}cells.push(cell);return cells}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,"").trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const headers=splitCsvLine(lines[0]).map(header=>header.trim());return lines.slice(1).map(line=>{const values=splitCsvLine(line);return Object.fromEntries(headers.map((header,index)=>[header,(values[index]||"").trim()]))})}
async function loadCsv(path){const response=await fetch(path);if(!response.ok)throw new Error(`${path} yüklenemedi`);return parseCsv(await response.text())}
function parseMatchDate(dateText,timeText="00:00"){return WorldCupDateTime.parse(dateText,timeText)}
function isPlayed(match){const home=String(match.home_score??"").trim(),away=String(match.away_score??"").trim();return home!==""&&away!==""&&Number.isFinite(Number(home))&&Number.isFinite(Number(away))}
function dayLabel(match){const date=parseMatchDate(match.match_date,match.match_time);if(!date)return"Yaklaşan";const difference=WorldCupDateTime.dayDifference(date);if(difference===0)return"Bugün";if(difference===1)return"Yarın";return"Yaklaşan"}
function countdown(match,now=new Date()){const date=parseMatchDate(match.match_date,match.match_time);if(!date)return"";const difference=date-now;if(difference<=0){const elapsed=now-date;return elapsed<=3*3600000?"Maç başladı":"Sonuç bekleniyor"}if(difference<=15*60000)return"Başlamak üzere";const totalHours=Math.ceil(difference/3600000),days=Math.floor(totalHours/24),hours=totalHours%24;return days?`${days} gün ${hours} saat kaldı`:`${hours} saat kaldı`}
function formatDate(match){return WorldCupDateTime.formatMatch(match)}
function buildTeamMeta(teams){state.teamMeta=new Map(teams.map(team=>{const name=canonicalTeam(team.team_name||team.team||team.name);return[normalize(name),{...team,team_name:name,group_name:normalizeGroup(team.group_name||team.group)}]}))}
function teamWithFlag(teamName){const name=canonicalTeam(teamName||"TBD"),meta=state.teamMeta.get(normalize(name)),flag=meta?.flag,image=flag?`<img class="flag-icon" src="${escapeHtml(flag)}" alt="">`:"",favorite=normalize(name)===normalize(state.favoriteTeam)?'<span class="favorite-star" aria-label="Favori takım">★</span>':"";return`${image}<a class="team-link" href="team.html?team=${encodeURIComponent(name)}">${escapeHtml(name)}</a>${favorite}`}
function matchMeta(match,includeCountdown=false){const parts=[formatDate(match),roundLabels[match.stage]||(match.stage==="Group"?"Grup aşaması":match.stage),match.group_name?`Grup ${normalizeGroup(match.group_name)}`:"",match.city].filter(Boolean);if(includeCountdown)parts.push(countdown(match));return parts.filter(Boolean).join(" • ")}
function createMatchCard(match,options={}){const card=document.createElement("article");card.className="match-item";const label=dayLabel(match),tagClass=label==="Bugün"?"tag-today":label==="Yarın"?"tag-tomorrow":"",tag=options.dayTag?`<div class="match-tag ${tagClass}">${label}</div>`:"",resultTag=options.resultIndex?`<div class="result-tag">Sonuç #${options.resultIndex}</div>`:"";card.innerHTML=`${tag}${resultTag}<div class="match-meta">${escapeHtml(matchMeta(match,options.dayTag))}</div><div class="match-line"><div class="team-name">${teamWithFlag(match.home_team)}</div><div class="score">${escapeHtml(match.home_score||"-")}</div></div><div class="match-line"><div class="team-name">${teamWithFlag(match.away_team)}</div><div class="score">${escapeHtml(match.away_score||"-")}</div></div>`;return card}
function filteredUpcoming(){return state.upcoming.filter(match=>{if(state.dayFilter==="today"&&dayLabel(match)!=="Bugün")return false;if(state.dayFilter==="tomorrow"&&dayLabel(match)!=="Yarın")return false;if(state.stageFilter==="Group"&&match.stage!=="Group")return false;if(state.stageFilter==="knockout"&&match.stage==="Group")return false;if(state.favoriteOnly&&state.favoriteTeam&&!matchIncludesTeam(match,state.favoriteTeam))return false;if(state.search){const searchable=[match.home_team,match.away_team,match.city,match.venue,match.group_name,match.stage].join(" ").toLocaleLowerCase("tr-TR");if(!searchable.includes(state.search))return false}return true})}
function matchIncludesTeam(match,team){const target=normalize(canonicalTeam(team));return[match.home_team,match.away_team].some(name=>normalize(canonicalTeam(name))===target)}
function readFavoriteTeam(){try{return localStorage.getItem(favoriteStorageKey)||""}catch(error){return""}}
function saveFavoriteTeam(team){try{team?localStorage.setItem(favoriteStorageKey,team):localStorage.removeItem(favoriteStorageKey)}catch(error){}}
function setupFavoriteControl(teams){const select=$("favoriteTeamSelect"),button=$("favoriteOnlyBtn");const names=teams.map(team=>canonicalTeam(team.team_name||team.team||team.name)).filter(Boolean).sort((a,b)=>a.localeCompare(b,"tr"));select.replaceChildren(new Option("Favori takım seç",""),...names.map(name=>new Option(name,name)));state.favoriteTeam=readFavoriteTeam();if(state.favoriteTeam&&!names.some(name=>normalize(name)===normalize(state.favoriteTeam)))state.favoriteTeam="";select.value=state.favoriteTeam;button.disabled=!state.favoriteTeam;button.classList.toggle("active",state.favoriteOnly);select.addEventListener("change",event=>{state.favoriteTeam=event.target.value;state.favoriteOnly=Boolean(state.favoriteTeam);saveFavoriteTeam(state.favoriteTeam);button.disabled=!state.favoriteTeam;button.classList.toggle("active",state.favoriteOnly);state.showAllUpcoming=false;renderUpcoming();renderResults()});button.addEventListener("click",()=>{if(!state.favoriteTeam)return;state.favoriteOnly=!state.favoriteOnly;button.classList.toggle("active",state.favoriteOnly);state.showAllUpcoming=false;renderUpcoming()})}
function renderUpcoming(){const container=$("nextMatches"),toggle=$("nextToggleBtn"),matches=filteredUpcoming(),visible=state.showAllUpcoming?matches:matches.slice(0,10);container.replaceChildren(...visible.map(match=>createMatchCard(match,{dayTag:true})));["All","Today","Tomorrow"].forEach(name=>{const value=name.toLowerCase()==="all"?"all":name.toLowerCase();$(`filter${name}Btn`).classList.toggle("active",state.dayFilter===value)});$("nextMatchesCount").textContent=matches.length?`${matches.length} maçtan ${visible.length} tanesi gösteriliyor`:"0 maç";if(!matches.length)container.innerHTML='<div class="empty-note">Bu filtrelere uygun maç bulunamadı.</div>';toggle.style.display=matches.length>10?"block":"none";toggle.textContent=state.showAllUpcoming?"Daha az göster":"Daha fazla göster"}
function renderResults(){const container=$("recentResults"),toggle=$("recentToggleBtn"),visible=state.showAllResults?state.results:state.results.slice(0,10);container.replaceChildren(...visible.map((match,index)=>createMatchCard(match,{resultIndex:index+1})));$("recentResultsCount").textContent=`${state.results.length} sonuç`;if(!state.results.length)container.innerHTML='<div class="empty-note">Henüz tamamlanan maç bulunmuyor.</div>';toggle.classList.toggle("disabled",state.results.length<=10);toggle.textContent=state.showAllResults?"Daha az göster":"Daha fazla göster"}
function createStanding(group,team){return{group,team,played:0,won:0,draw:0,lost:0,gf:0,ga:0,gd:0,points:0,rank:0}}
function buildStandings(teams,matches){const groups=new Map();teams.forEach(team=>{const group=normalizeGroup(team.group_name||team.group),name=canonicalTeam(team.team_name||team.team);if(!group||!name)return;if(!groups.has(group))groups.set(group,new Map());groups.get(group).set(name,createStanding(group,name))});matches.filter(match=>match.stage==="Group"&&isPlayed(match)).forEach(match=>{const group=normalizeGroup(match.group_name);if(!groups.has(group))groups.set(group,new Map());const rows=groups.get(group),homeName=canonicalTeam(match.home_team),awayName=canonicalTeam(match.away_team);if(!rows.has(homeName))rows.set(homeName,createStanding(group,homeName));if(!rows.has(awayName))rows.set(awayName,createStanding(group,awayName));const home=rows.get(homeName),away=rows.get(awayName),homeScore=Number(match.home_score),awayScore=Number(match.away_score);home.played+=1;away.played+=1;home.gf+=homeScore;home.ga+=awayScore;away.gf+=awayScore;away.ga+=homeScore;if(homeScore>awayScore){home.won+=1;home.points+=3;away.lost+=1}else if(awayScore>homeScore){away.won+=1;away.points+=3;home.lost+=1}else{home.draw+=1;away.draw+=1;home.points+=1;away.points+=1}});return new Map([...groups].map(([group,rowMap])=>{const rows=[...rowMap.values()].map(row=>({...row,gd:row.gf-row.ga}));rows.sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team));rows.forEach((row,index)=>{row.rank=index+1});return[group,rows]}))}
function renderLeaders(standings){const container=$("groupLeaders"),activeGroups=[...standings].filter(([,rows])=>rows.some(row=>row.played>0));if(!activeGroups.length){container.innerHTML='<div class="empty-note">Grup maçları tamamlandıkça liderler burada görünecek.</div>';return}container.innerHTML=activeGroups.map(([group,rows])=>{const leader=rows[0];return`<article class="leader-item"><div class="leader-title">Grup ${group}: ${teamWithFlag(leader.team)}</div><div class="leader-meta">Sıra: 1 • Puan: ${leader.points}</div><div class="leader-stats"><div class="leader-stat-box"><div class="leader-stat-label">Maç</div><div class="leader-stat-value">${leader.played}</div></div><div class="leader-stat-box"><div class="leader-stat-label">Averaj</div><div class="leader-stat-value">${leader.gd}</div></div><div class="leader-stat-box"><div class="leader-stat-label">Attığı gol</div><div class="leader-stat-value">${leader.gf}</div></div></div><div class="leader-extra">G-B-M: ${leader.won}-${leader.draw}-${leader.lost}<br>Goller: ${leader.gf} attı / ${leader.ga} yedi</div></article>`}).join("")}
function renderGroups(standings){$("groupsGrid").innerHTML=[...standings].sort(([a],[b])=>a.localeCompare(b)).map(([group,rows])=>`<article class="group-card"><div class="group-title">Grup ${group}</div><table class="group-table"><thead><tr><th>#</th><th>Takım</th><th>O</th><th>G</th><th>B</th><th>M</th><th>AG</th><th>YG</th><th>AV</th><th>P</th></tr></thead><tbody>${rows.map(row=>`<tr class="${row.rank===1?"group-winner":row.rank===2?"group-qualified":""}"><td>${row.rank}</td><td>${teamWithFlag(row.team)}</td><td>${row.played}</td><td>${row.won}</td><td>${row.draw}</td><td>${row.lost}</td><td>${row.gf}</td><td>${row.ga}</td><td>${row.gd}</td><td>${row.points}</td></tr>`).join("")}</tbody></table></article>`).join("")}
function knockoutWinner(match){if(!isPlayed(match))return null;if(Number(match.home_score)>Number(match.away_score))return"home";if(Number(match.away_score)>Number(match.home_score))return"away";return null}
function bracketCard(match,isFinal=false){const winner=knockoutWinner(match);return`<article class="bracket-match-card ${isFinal?"main-final":""}"><div class="bracket-meta">${escapeHtml([formatDate(match),match.city,match.venue].filter(Boolean).join(" • "))}</div><div class="bracket-team-row ${winner==="home"?"winner-row":""}"><div class="team-name">${winner==="home"?"✓ ":""}${teamWithFlag(match.home_team)}</div><div class="score">${escapeHtml(match.home_score||"-")}</div></div><div class="bracket-team-row ${winner==="away"?"winner-row":""}"><div class="team-name">${winner==="away"?"✓ ":""}${teamWithFlag(match.away_team)}</div><div class="score">${escapeHtml(match.away_score||"-")}</div></div></article>`}
function renderBracket(matches){const byRound=new Map([...knockoutRounds,"Third place"].map(round=>[round,[]]));matches.forEach(match=>{if(byRound.has(match.stage))byRound.get(match.stage).push(match)});byRound.forEach(roundMatches=>roundMatches.sort((a,b)=>parseMatchDate(a.match_date,a.match_time)-parseMatchDate(b.match_date,b.match_time)));const columns=knockoutRounds.filter(round=>byRound.get(round).length).map(round=>{const isFinal=round==="Final",thirdPlace=isFinal&&byRound.get("Third place").length?`<div class="third-place-block"><div class="third-place-label">${roundLabels["Third place"]}</div>${byRound.get("Third place").map(match=>bracketCard(match)).join("")}</div>`:"";return`<section class="round-column ${isFinal?"final-column":""}"><div class="round-title">${roundLabels[round]}</div><div class="bracket-match-list">${byRound.get(round).map(match=>bracketCard(match,isFinal)).join("")}</div>${thirdPlace}</section>`});$("bracket").innerHTML=columns.length?columns.join(""):'<div class="empty-note">Eleme aşaması maçları henüz bulunmuyor.</div>'}
function renderSummary(teams,matches){const nextMatch=matches.filter(match=>!isPlayed(match)).map(match=>({match,date:parseMatchDate(match.match_date,match.match_time)})).filter(item=>item.date&&item.date>=new Date()).sort((a,b)=>a.date-b.date)[0]?.match;$("statTeams").textContent=teams.length;$("statMatches").textContent=matches.length;$("statPlayed").textContent=matches.filter(isPlayed).length;$("statNextMatch").textContent=nextMatch?`${canonicalTeam(nextMatch.home_team)} - ${canonicalTeam(nextMatch.away_team)} • ${countdown(nextMatch)}`:"Planlanmış maç bulunmuyor"}
function setDayFilter(filter){state.dayFilter=filter;state.showAllUpcoming=false;renderUpcoming()}
function bindControls(){$("filterAllBtn").addEventListener("click",()=>setDayFilter("all"));$("filterTodayBtn").addEventListener("click",()=>setDayFilter("today"));$("filterTomorrowBtn").addEventListener("click",()=>setDayFilter("tomorrow"));$("matchSearch").addEventListener("input",event=>{state.search=event.target.value.trim().toLocaleLowerCase("tr-TR");state.showAllUpcoming=false;renderUpcoming()});$("stageFilter").addEventListener("change",event=>{state.stageFilter=event.target.value;state.showAllUpcoming=false;renderUpcoming()});$("nextToggleBtn").addEventListener("click",()=>{state.showAllUpcoming=!state.showAllUpcoming;renderUpcoming()});$("recentToggleBtn").addEventListener("click",()=>{state.showAllResults=!state.showAllResults;renderResults()})}
async function init(){try{const[teams,matches]=await Promise.all([loadCsv("teams.csv"),loadCsv("matches.csv")]);buildTeamMeta(teams);setupFavoriteControl(teams);state.upcoming=matches.filter(match=>!isPlayed(match)).sort((a,b)=>parseMatchDate(a.match_date,a.match_time)-parseMatchDate(b.match_date,b.match_time));state.results=matches.filter(isPlayed).sort((a,b)=>parseMatchDate(b.match_date,b.match_time)-parseMatchDate(a.match_date,a.match_time));const standings=buildStandings(teams,matches);renderSummary(teams,matches);renderUpcoming();renderResults();renderLeaders(standings);renderGroups(standings);renderBracket(matches);bindControls();$("status").className="status success";$("status").textContent="Veriler başarıyla yüklendi."}catch(error){console.error(error);$("status").className="status error";$("status").textContent=`Hata: ${error.message}`}}
init();
